# dredd.yml
endpoint: "http://localhost:3000/api/v1"

blueprint: "./packages/core-contracts/dist/openapi.json"

# Ensure no extra API description globs cause null entries
path: []

language: nodejs
hookfiles:
  - "./dredd-hooks.js"

reporter:
  - dot

loglevel: debug
